# Generated by Django 3.2.6 on 2022-02-03 10:17

from django.db import migrations, models
import movieapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField(validators=[movieapi.models.round_up_rating])),
                ('release', models.DateField()),
                ('duration', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Movies',
                'ordering': ('name', 'rating', 'release', 'duration', 'description'),
                'unique_together': {('name', 'release')},
            },
        ),
    ]
